// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knn_predict_classif_gower_cpp
Rcpp::List knn_predict_classif_gower_cpp(const arma::mat& Xnum_train, const arma::imat& Xcat_train, const arma::mat& Xord_train, const arma::mat& Xnum_test, const arma::imat& Xcat_test, const arma::mat& Xord_test, const arma::rowvec& ranges_num, const Rcpp::IntegerVector& y_train, const int k, const std::string& weight_scheme, const double min_feature_frac, const Rcpp::NumericVector& priors);
RcppExport SEXP _mlr3mbspls_knn_predict_classif_gower_cpp(SEXP Xnum_trainSEXP, SEXP Xcat_trainSEXP, SEXP Xord_trainSEXP, SEXP Xnum_testSEXP, SEXP Xcat_testSEXP, SEXP Xord_testSEXP, SEXP ranges_numSEXP, SEXP y_trainSEXP, SEXP kSEXP, SEXP weight_schemeSEXP, SEXP min_feature_fracSEXP, SEXP priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnum_train(Xnum_trainSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Xcat_train(Xcat_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xord_train(Xord_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnum_test(Xnum_testSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Xcat_test(Xcat_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xord_test(Xord_testSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ranges_num(ranges_numSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type weight_scheme(weight_schemeSEXP);
    Rcpp::traits::input_parameter< const double >::type min_feature_frac(min_feature_fracSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priors(priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_predict_classif_gower_cpp(Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, priors));
    return rcpp_result_gen;
END_RCPP
}
// knn_predict_regr_gower_cpp
Rcpp::List knn_predict_regr_gower_cpp(const arma::mat& Xnum_train, const arma::imat& Xcat_train, const arma::mat& Xord_train, const arma::mat& Xnum_test, const arma::imat& Xcat_test, const arma::mat& Xord_test, const arma::rowvec& ranges_num, const arma::vec& y_train, const int k, const std::string& weight_scheme, const double min_feature_frac, const double fallback_mean, const double fallback_var);
RcppExport SEXP _mlr3mbspls_knn_predict_regr_gower_cpp(SEXP Xnum_trainSEXP, SEXP Xcat_trainSEXP, SEXP Xord_trainSEXP, SEXP Xnum_testSEXP, SEXP Xcat_testSEXP, SEXP Xord_testSEXP, SEXP ranges_numSEXP, SEXP y_trainSEXP, SEXP kSEXP, SEXP weight_schemeSEXP, SEXP min_feature_fracSEXP, SEXP fallback_meanSEXP, SEXP fallback_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnum_train(Xnum_trainSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Xcat_train(Xcat_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xord_train(Xord_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnum_test(Xnum_testSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Xcat_test(Xcat_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xord_test(Xord_testSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ranges_num(ranges_numSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type weight_scheme(weight_schemeSEXP);
    Rcpp::traits::input_parameter< const double >::type min_feature_frac(min_feature_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type fallback_mean(fallback_meanSEXP);
    Rcpp::traits::input_parameter< const double >::type fallback_var(fallback_varSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_predict_regr_gower_cpp(Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, fallback_mean, fallback_var));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mbspca_one_lv
Rcpp::List cpp_mbspca_one_lv(const Rcpp::List& X_blocks, const arma::vec& c_vec, int max_iter, double tol);
RcppExport SEXP _mlr3mbspls_cpp_mbspca_one_lv(SEXP X_blocksSEXP, SEXP c_vecSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_vec(c_vecSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mbspca_one_lv(X_blocks, c_vec, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// perm_test_component_mbspca
double perm_test_component_mbspca(const Rcpp::List& X_blocks, const Rcpp::List& W_list, const arma::vec& c_vec, int n_perm, double alpha, int max_iter, double tol);
RcppExport SEXP _mlr3mbspls_perm_test_component_mbspca(SEXP X_blocksSEXP, SEXP W_listSEXP, SEXP c_vecSEXP, SEXP n_permSEXP, SEXP alphaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_vec(c_vecSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_test_component_mbspca(X_blocks, W_list, c_vec, n_perm, alpha, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_block_objective_oos
double cpp_block_objective_oos(const Rcpp::List& X_blocks, const Rcpp::List& W_list, bool spearman, bool frobenius);
RcppExport SEXP _mlr3mbspls_cpp_block_objective_oos(SEXP X_blocksSEXP, SEXP W_listSEXP, SEXP spearmanSEXP, SEXP frobeniusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_block_objective_oos(X_blocks, W_list, spearman, frobenius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mbspls_start_weights
Rcpp::List cpp_mbspls_start_weights(const Rcpp::List& X_blocks, const arma::vec& c_constraints);
RcppExport SEXP _mlr3mbspls_cpp_mbspls_start_weights(SEXP X_blocksSEXP, SEXP c_constraintsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_constraints(c_constraintsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mbspls_start_weights(X_blocks, c_constraints));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mbspls_one_lv
Rcpp::List cpp_mbspls_one_lv(const Rcpp::List& X_blocks, const arma::vec& c_constraints, int max_iter, double tol, bool frobenius, bool spearman);
RcppExport SEXP _mlr3mbspls_cpp_mbspls_one_lv(SEXP X_blocksSEXP, SEXP c_constraintsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP frobeniusSEXP, SEXP spearmanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_constraints(c_constraintsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mbspls_one_lv(X_blocks, c_constraints, max_iter, tol, frobenius, spearman));
    return rcpp_result_gen;
END_RCPP
}
// perm_test_component
double perm_test_component(const std::vector<arma::mat>& X_orig, const std::vector<arma::vec>& W_orig, const arma::vec& c_vec, int n_perm, bool spearman, int max_iter, double tol, double early_stop_threshold, bool frobenius);
RcppExport SEXP _mlr3mbspls_perm_test_component(SEXP X_origSEXP, SEXP W_origSEXP, SEXP c_vecSEXP, SEXP n_permSEXP, SEXP spearmanSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP early_stop_thresholdSEXP, SEXP frobeniusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type X_orig(X_origSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::vec>& >::type W_orig(W_origSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_vec(c_vecSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type early_stop_threshold(early_stop_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_test_component(X_orig, W_orig, c_vec, n_perm, spearman, max_iter, tol, early_stop_threshold, frobenius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mbspls_multi_lv
Rcpp::List cpp_mbspls_multi_lv(const Rcpp::List& X_blocks, const arma::vec& c_constraints, int K, int max_iter, double tol, bool spearman, bool do_perm, int n_perm, double alpha, bool frobenius);
RcppExport SEXP _mlr3mbspls_cpp_mbspls_multi_lv(SEXP X_blocksSEXP, SEXP c_constraintsSEXP, SEXP KSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP spearmanSEXP, SEXP do_permSEXP, SEXP n_permSEXP, SEXP alphaSEXP, SEXP frobeniusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_constraints(c_constraintsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type do_perm(do_permSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mbspls_multi_lv(X_blocks, c_constraints, K, max_iter, tol, spearman, do_perm, n_perm, alpha, frobenius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mbspls_multi_lv_cmatrix
Rcpp::List cpp_mbspls_multi_lv_cmatrix(const Rcpp::List& X_blocks, const arma::mat& c_matrix, int max_iter, double tol, bool spearman, bool do_perm, int n_perm, double alpha, bool frobenius);
RcppExport SEXP _mlr3mbspls_cpp_mbspls_multi_lv_cmatrix(SEXP X_blocksSEXP, SEXP c_matrixSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP spearmanSEXP, SEXP do_permSEXP, SEXP n_permSEXP, SEXP alphaSEXP, SEXP frobeniusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks(X_blocksSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type c_matrix(c_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type do_perm(do_permSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mbspls_multi_lv_cmatrix(X_blocks, c_matrix, max_iter, tol, spearman, do_perm, n_perm, alpha, frobenius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_test_ev_core
Rcpp::List cpp_compute_test_ev_core(const Rcpp::List& X_blocks_test, const Rcpp::List& W_all, const Rcpp::List& P_all, bool deflate, bool spearman, bool frobenius, double eps_var, bool use_train_loadings, int clamp_mode);
RcppExport SEXP _mlr3mbspls_cpp_compute_test_ev_core(SEXP X_blocks_testSEXP, SEXP W_allSEXP, SEXP P_allSEXP, SEXP deflateSEXP, SEXP spearmanSEXP, SEXP frobeniusSEXP, SEXP eps_varSEXP, SEXP use_train_loadingsSEXP, SEXP clamp_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_blocks_test(X_blocks_testSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type W_all(W_allSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type P_all(P_allSEXP);
    Rcpp::traits::input_parameter< bool >::type deflate(deflateSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    Rcpp::traits::input_parameter< double >::type eps_var(eps_varSEXP);
    Rcpp::traits::input_parameter< bool >::type use_train_loadings(use_train_loadingsSEXP);
    Rcpp::traits::input_parameter< int >::type clamp_mode(clamp_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_test_ev_core(X_blocks_test, W_all, P_all, deflate, spearman, frobenius, eps_var, use_train_loadings, clamp_mode));
    return rcpp_result_gen;
END_RCPP
}
// cpp_perm_test_oos
Rcpp::List cpp_perm_test_oos(const Rcpp::List& X_test, const Rcpp::List& W_trained, int n_perm, bool spearman, bool frobenius, double early_stop_threshold, bool permute_all_blocks);
RcppExport SEXP _mlr3mbspls_cpp_perm_test_oos(SEXP X_testSEXP, SEXP W_trainedSEXP, SEXP n_permSEXP, SEXP spearmanSEXP, SEXP frobeniusSEXP, SEXP early_stop_thresholdSEXP, SEXP permute_all_blocksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type W_trained(W_trainedSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    Rcpp::traits::input_parameter< double >::type early_stop_threshold(early_stop_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type permute_all_blocks(permute_all_blocksSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_perm_test_oos(X_test, W_trained, n_perm, spearman, frobenius, early_stop_threshold, permute_all_blocks));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bootstrap_test_oos
Rcpp::List cpp_bootstrap_test_oos(const Rcpp::List& X_test, const Rcpp::List& W_trained, int n_boot, bool spearman, bool frobenius, double alpha);
RcppExport SEXP _mlr3mbspls_cpp_bootstrap_test_oos(SEXP X_testSEXP, SEXP W_trainedSEXP, SEXP n_bootSEXP, SEXP spearmanSEXP, SEXP frobeniusSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type W_trained(W_trainedSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< bool >::type frobenius(frobeniusSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bootstrap_test_oos(X_test, W_trained, n_boot, spearman, frobenius, alpha));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lm_coeff_ridge
arma::mat cpp_lm_coeff_ridge(const arma::mat& X, const arma::mat& Y, const double lambda, Rcpp::Nullable<Rcpp::IntegerVector> unpen_idx);
RcppExport SEXP _mlr3mbspls_cpp_lm_coeff_ridge(SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP unpen_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type unpen_idx(unpen_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lm_coeff_ridge(X, Y, lambda, unpen_idx));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lm_coeff
arma::mat cpp_lm_coeff(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _mlr3mbspls_cpp_lm_coeff(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lm_coeff(X, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlr3mbspls_knn_predict_classif_gower_cpp", (DL_FUNC) &_mlr3mbspls_knn_predict_classif_gower_cpp, 12},
    {"_mlr3mbspls_knn_predict_regr_gower_cpp", (DL_FUNC) &_mlr3mbspls_knn_predict_regr_gower_cpp, 13},
    {"_mlr3mbspls_cpp_mbspca_one_lv", (DL_FUNC) &_mlr3mbspls_cpp_mbspca_one_lv, 4},
    {"_mlr3mbspls_perm_test_component_mbspca", (DL_FUNC) &_mlr3mbspls_perm_test_component_mbspca, 7},
    {"_mlr3mbspls_cpp_block_objective_oos", (DL_FUNC) &_mlr3mbspls_cpp_block_objective_oos, 4},
    {"_mlr3mbspls_cpp_mbspls_start_weights", (DL_FUNC) &_mlr3mbspls_cpp_mbspls_start_weights, 2},
    {"_mlr3mbspls_cpp_mbspls_one_lv", (DL_FUNC) &_mlr3mbspls_cpp_mbspls_one_lv, 6},
    {"_mlr3mbspls_perm_test_component", (DL_FUNC) &_mlr3mbspls_perm_test_component, 9},
    {"_mlr3mbspls_cpp_mbspls_multi_lv", (DL_FUNC) &_mlr3mbspls_cpp_mbspls_multi_lv, 10},
    {"_mlr3mbspls_cpp_mbspls_multi_lv_cmatrix", (DL_FUNC) &_mlr3mbspls_cpp_mbspls_multi_lv_cmatrix, 9},
    {"_mlr3mbspls_cpp_compute_test_ev_core", (DL_FUNC) &_mlr3mbspls_cpp_compute_test_ev_core, 9},
    {"_mlr3mbspls_cpp_perm_test_oos", (DL_FUNC) &_mlr3mbspls_cpp_perm_test_oos, 7},
    {"_mlr3mbspls_cpp_bootstrap_test_oos", (DL_FUNC) &_mlr3mbspls_cpp_bootstrap_test_oos, 6},
    {"_mlr3mbspls_cpp_lm_coeff_ridge", (DL_FUNC) &_mlr3mbspls_cpp_lm_coeff_ridge, 4},
    {"_mlr3mbspls_cpp_lm_coeff", (DL_FUNC) &_mlr3mbspls_cpp_lm_coeff, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlr3mbspls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
