# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_predict_classif_gower_cpp <- function(Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, priors) {
    .Call(`_mlr3mbspls_knn_predict_classif_gower_cpp`, Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, priors)
}

knn_predict_regr_gower_cpp <- function(Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, fallback_mean, fallback_var) {
    .Call(`_mlr3mbspls_knn_predict_regr_gower_cpp`, Xnum_train, Xcat_train, Xord_train, Xnum_test, Xcat_test, Xord_test, ranges_num, y_train, k, weight_scheme, min_feature_frac, fallback_mean, fallback_var)
}

cpp_mbspca_one_lv <- function(X_blocks, c_vec, max_iter = 50L, tol = 1e-4) {
    .Call(`_mlr3mbspls_cpp_mbspca_one_lv`, X_blocks, c_vec, max_iter, tol)
}

perm_test_component_mbspca <- function(X_blocks, W_list, c_vec, n_perm = 999L, alpha = 0.05) {
    .Call(`_mlr3mbspls_perm_test_component_mbspca`, X_blocks, W_list, c_vec, n_perm, alpha)
}

cpp_mbspls_one_lv <- function(X_blocks, c_constraints, max_iter, tol, frobenius = FALSE, spearman = FALSE) {
    .Call(`_mlr3mbspls_cpp_mbspls_one_lv`, X_blocks, c_constraints, max_iter, tol, frobenius, spearman)
}

perm_test_component <- function(X_orig, W_orig, c_vec, n_perm = 1000L, spearman = FALSE, max_iter = 500L, tol = 1e-4, early_stop_threshold = 0.05, frobenius = FALSE) {
    .Call(`_mlr3mbspls_perm_test_component`, X_orig, W_orig, c_vec, n_perm, spearman, max_iter, tol, early_stop_threshold, frobenius)
}

cpp_mbspls_multi_lv <- function(X_blocks, c_constraints, K = 2L, max_iter = 500L, tol = 1e-4, spearman = FALSE, do_perm = FALSE, n_perm = 100L, alpha = 0.05, frobenius = FALSE) {
    .Call(`_mlr3mbspls_cpp_mbspls_multi_lv`, X_blocks, c_constraints, K, max_iter, tol, spearman, do_perm, n_perm, alpha, frobenius)
}

cpp_mbspls_multi_lv_cmatrix <- function(X_blocks, c_matrix, max_iter = 500L, tol = 1e-4, spearman = FALSE, do_perm = FALSE, n_perm = 100L, alpha = 0.05, frobenius = FALSE) {
    .Call(`_mlr3mbspls_cpp_mbspls_multi_lv_cmatrix`, X_blocks, c_matrix, max_iter, tol, spearman, do_perm, n_perm, alpha, frobenius)
}

cpp_ev_test <- function(X_test, weights, loadings, ncomp) {
    .Call(`_mlr3mbspls_cpp_ev_test`, X_test, weights, loadings, ncomp)
}

cpp_mbspls_bootstrap <- function(X_blocks, c_constraints, W_ref, R = 500L, spearman = FALSE, frobenius = FALSE, max_iter = 500L, tol = 1e-6, store_weights = TRUE) {
    .Call(`_mlr3mbspls_cpp_mbspls_bootstrap`, X_blocks, c_constraints, W_ref, R, spearman, frobenius, max_iter, tol, store_weights)
}

cpp_bootstrap_latent_correlation <- function(weights_matrix, component_idx, block_idx, n_blocks, n_components, spearman = FALSE, min_var = 1e-12, frobenius = FALSE) {
    .Call(`_mlr3mbspls_cpp_bootstrap_latent_correlation`, weights_matrix, component_idx, block_idx, n_blocks, n_components, spearman, min_var, frobenius)
}

cpp_perm_test_oos <- function(X_test, W_trained, n_perm = 1000L, spearman = FALSE, frobenius = FALSE, early_stop_threshold = 1.0, permute_all_blocks = TRUE) {
    .Call(`_mlr3mbspls_cpp_perm_test_oos`, X_test, W_trained, n_perm, spearman, frobenius, early_stop_threshold, permute_all_blocks)
}

cpp_lm_coeff_ridge <- function(X, Y, lambda, unpen_idx) {
    .Call(`_mlr3mbspls_cpp_lm_coeff_ridge`, X, Y, lambda, unpen_idx)
}

cpp_lm_coeff <- function(X, Y) {
    .Call(`_mlr3mbspls_cpp_lm_coeff`, X, Y)
}

