# pkgdown workflow (inspired by the mlr3 ecosystem workflows)
# https://github.com/mlr-org/mlr3/tree/main/.github/workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

name: pkgdown

permissions:
  contents: read

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: r-lib/actions/setup-pandoc@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2

      - uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2

      - uses: r-lib/actions/setup-r-dependencies@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          extra-packages: any::pkgdown, local::., mixOmics=?ignore, multiblock=?ignore, neuroCombat=?ignore, BiocParallel=?ignore
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Upload site artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pkgdown-site
          path: docs

  deploy:
    if: github.event_name != 'pull_request'
    needs: pkgdown
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: pkgdown-deploy
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Download site artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: pkgdown-site
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
